### ISSUE TITLE
Any plans on supporting Debian 8?

### ISSUE THREAD

**Issue by sbakker** [CERIT-SC/puppet-serial_console#1]
Hi,
I was wondering if there are any plans on supporting Debian 8 (jessie) in your module. I notice that the source of params.pp contains an explicit check for Debian 6 or 7, so it will fail on any other version.

Debian 8 no longer uses inittab, but systemd is smart enough to see the "console=ttyS0" kernel command line and start a getty on that device, so it shouldn't be too hard to include support for Debian 8 (he said with hope in his eyes).

Cjeers,
Steven

**Comment by vholer** [comment]
I have merged your commits, I'll do some cleanups and release new version on Puppet Forge.
Thank you for contribution!
